### Numpy Broadcasting

In [1]:
import numpy as np

In [7]:
a = np.array([[1,2,3,4],
              [2,4,5,6],
              [10,20,30,40]])
b = np.array([2,4,6,8])
print(a)
print(a.shape)
print("--------------------------------")
print(b)
print(b.shape)
print("--------------------------------")
print(a+b)
print("--------------------------------")
print(a-b)
print("--------------------------------")
print(a/b)
print("--------------------------------")
print(a*b)
print("--------------------------------")

[[ 1  2  3  4]
 [ 2  4  5  6]
 [10 20 30 40]]
(3, 4)
--------------------------------
[2 4 6 8]
(4,)
--------------------------------
[[ 3  6  9 12]
 [ 4  8 11 14]
 [12 24 36 48]]
--------------------------------
[[-1 -2 -3 -4]
 [ 0  0 -1 -2]
 [ 8 16 24 32]]
--------------------------------
[[0.5        0.5        0.5        0.5       ]
 [1.         1.         0.83333333 0.75      ]
 [5.         5.         5.         5.        ]]
--------------------------------
[[  2   8  18  32]
 [  4  16  30  48]
 [ 20  80 180 320]]
--------------------------------


In [14]:
arr1 = np.arange(15).reshape(5,3)
print(arr1)
print("-" * 20)
arr2 = np.arange(5).reshape(5,1)
print(arr2)
print("-" * 20)
print(arr1 + arr2)


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
--------------------
[[0]
 [1]
 [2]
 [3]
 [4]]
--------------------
[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]
 [16 17 18]]


In [17]:
a = np.array([[1,2,3,4],
             [5,6,7,8],
             [9,10,11,12]])
print(a)
print("-" * 20)
at = a.T
print(at)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
--------------------
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [19]:
a = np.array(['apple','banana','mango'])
print(a)
print(a.dtype)

['apple' 'banana' 'mango']
<U6


In [20]:
a = np.array([['welcome'],
              ['hi']])
print(a)

[['welcome']
 ['hi']]


In [22]:
print(np.char.add(['welcome'],['hi']))

['welcomehi']


In [26]:
a = np.array(['hello', ' '])
b = np.array(['world' , 'numpy'])
result = np.char.add(a,b)
print(result)

['helloworld' ' numpy']


### Rounding Functions

### 1.round()

In [30]:
arr = np.array([3.2,3.6,7.89,3.5])
print(np.round(arr))

[3. 4. 8. 4.]
[3. 3. 7. 3.]


### 2.floor()

In [32]:
arr1 = np.array([3.9,2.5,-1.2,7.7])
print(np.floor(arr1))

[ 3.  2. -2.  7.]


### 3.ceil()

In [33]:
arr2 = np.array([3.1,2.8,-1.2,4.5])
print(np.ceil(arr2))

[ 4.  3. -1.  5.]


### np.where()

In [38]:
marks = np.array([40,50,75,30,80])

positions = np.where(marks>50)
print("Index positions :" , positions)

# Same like if-else logic
result = np.where(marks >= 50 , 'Pass' , 'Fail')
print("Result:",result)

Index positions : (array([2, 4]),)
Result: ['Fail' 'Pass' 'Pass' 'Fail' 'Pass']


### np.any()

In [44]:
arr1 = np.array([0,0,5,0])
print(np.any(arr1))

arr2 = np.array([0,0,0,0])
print(np.any(arr2))

arr3 = np.array([[0,0],
                 [0,2]])
print(np.any(arr3))
arr4 = np.array([[0,0],
                 [0,0]])
print(np.any(arr4))

True
False
True
False
