### mean()

In [1]:
import numpy as np

In [3]:
arr = np.array([50,70,30,90,60])
average = np.mean(arr)
print("Mean Value:" , average)

Mean Value: 60.0


In [7]:
arr2d = np.array([[1,2,3],
                  [4,5,6]])
print("Mean of all elements:" , np.mean(arr2d))
print("Mean of all columns:" , np.mean(arr2d , axis = 0))
print("Mean of all columns:" , np.mean(arr2d , axis = 1))

Mean of all elements: 3.5
Mean of all columns: [2.5 3.5 4.5]
Mean of all columns: [2. 5.]


## median()

In [9]:
arr = np.array([50,70,30,90,60])
med = np.median(arr)
print("Median Value:" ,med)

Median Value: 60.0


In [11]:
arr2d = np.array([[1,2,3],
                  [4,5,6]])
med = np.median(arr2d)
print("Median of all elements:" , np.median(arr2d))
print("Median of all columns:" , np.median(arr2d , axis = 0))
print("Median of all columns:" , np.median(arr2d , axis = 1))

Median of all elements: 3.5
Median of all columns: [2.5 3.5 4.5]
Median of all columns: [2. 5.]


## variance()


In [13]:
marks = np.array([50,70,30,90,60])
print("Variance:" , np.var(marks))
print("Standard deviation:" , np.std(marks))

Variance: 400.0
Standard deviation: 20.0


In [16]:
arr2d = np.array([[1,2,3],
                  [4,5,6]])

print("Variance of entire array:" , np.var(arr2d))
print("Variance of row wise:" , np.var(arr2d , axis = 1))
print("Variance of column wise:" , np.var(arr2d , axis = 0))

Variance of entire array: 2.9166666666666665
Variance of row wise: [0.66666667 0.66666667]
Variance of column wise: [2.25 2.25 2.25]


## Standard deviation

In [18]:
marks = np.array([50,70,30,90,60])
print("Std dev:" , np.std(marks))

Std dev: 20.0


In [20]:
arr2d = np.array([[1,2,3],
                  [4,5,6]])

print("Std dev of entire array:" , np.std(arr2d))
print("Std dev  of row wise:" , np.std(arr2d , axis = 1))
print("Std dev of column wise:" , np.std(arr2d , axis = 0))

Std dev of entire array: 1.707825127659933
Std dev  of row wise: [0.81649658 0.81649658]
Std dev of column wise: [1.5 1.5 1.5]


### co-relation co-efficient

In [26]:
x = [1,2,3,4,5]
y = [2,4,6,8,10]

corr = np.corrcoef(x,y)
print(corr)

print("-----------------------")

x1 = [1,2,3,4,5]
y1 = [10,8,6,4,2]
corr1 = np.corrcoef(x1,y1)
print(corr1)

[[1. 1.]
 [1. 1.]]
-----------------------
[[ 1. -1.]
 [-1.  1.]]


### Vectorization

In [33]:
# Without numpy
marks = [50,60,70,80,90]
updated_marks = [x+5 for x in marks]
print(updated_marks)

#With Numpy
marks = np.array([50,60,70,80,90])
updated_marks1 = marks + 5
print(updated_marks1)

[55, 65, 75, 85, 95]
[55 65 75 85 95]


In [34]:
a = [1,2,3]
b = [4,5,6]
a+b

[1, 2, 3, 4, 5, 6]

In [35]:
a = np.array( [1,2,3])
b = np.array([4,5,6])
a+b

array([5, 7, 9])

## Array Manipulation

#### concatenate()

In [38]:
a = np.array([1,2,3])
b = np.array([4,5])
result = np.concatenate((a,b))
print(result)

[1 2 3 4 5]


In [49]:
# 2D Array

a =  np.array([[1,2],
               [3,4]])
b = np.array([[5,6],
              [7,8]])
#Row Wise
row_concat = np.concatenate((a,b) , axis = 0)
print("Row Wise :\n" , row_concat)
print("----------------------------")

# Column Wise
column_concat = np.concatenate((a,b),axis  = 1)
print("Column Wise:\n" , column_concat)
print("----------------------------")


Row Wise :
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
----------------------------
Column Wise:
 [[1 2 5 6]
 [3 4 7 8]]
----------------------------


### Vstack()

In [52]:
a = np.array([1,2,3])
b = np.array([4,5,6])

vstack1d = np.vstack((a,b))
print(vstack1d)

[[1 2 3]
 [4 5 6]]


In [53]:
#2D array

a = np.array([[1,2],
              [3,4]])
b = np.array([[5,6]])

vstack2d = np.vstack((a,b))
print(vstack2d)

[[1 2]
 [3 4]
 [5 6]]


### Hstack()

In [56]:
a = np.array([1,2,3])
b = np.array([4,5,6])

hstack1d = np.hstack((a,b))
print(hstack1d)

[1 2 3 4 5 6]


In [59]:
#2D array

a = np.array([[1,2],
              [3,4]])
b = np.array([[5,6],
              [7,8]])

hstack2d = np.hstack((a,b))
print(hstack2d)

[[1 2 5 6]
 [3 4 7 8]]


### column stack()

In [60]:
# 1D array
a = np.array([1,2,3])
b = np.array([4,5,6])

col_stack1d = np.column_stack((a,b))
print(col_stack1d)

[[1 4]
 [2 5]
 [3 6]]


In [62]:
#2D array

a = np.array([[1,2],
              [3,4]])
b = np.array([[5,6],
              [7,8]])

col_stack2d = np.column_stack((a,b))
print(col_stack2d)

[[1 2 5 6]
 [3 4 7 8]]


## Split()

### hsplit()

In [64]:
a = np.array([[1,2,3,4],
             [5,6,7,8]])

split_2 = np.hsplit(a,2)
print(split_2)
             

[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]


In [65]:
split_4 = np.hsplit(a,4)
print(split_4)

[array([[1],
       [5]]), array([[2],
       [6]]), array([[3],
       [7]]), array([[4],
       [8]])]


### vsplit()

In [68]:
a = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12],
              [13,14,15,16]])

split_2 = np.vsplit(a,2)
print(split_2)

[array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])]


In [70]:

split_4 = np.vsplit(a,4)
print(split_4)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]]), array([[13, 14, 15, 16]])]


## Sorting Arrays

In [73]:
arr = np.array([5,1,4,3,2])
sorted_arr = np.sort(arr)
print("Original array:" , arr)
print("Sorted array:", sorted_arr)
print("Descending array:" , sorted_arr[::-1])

Original array: [5 1 4 3 2]
Sorted array: [1 2 3 4 5]
Descending array: [5 4 3 2 1]


In [77]:
#2D Array

arr2d = np.array([[3,1,8],
                  [6,2,4]])
sorted_arr2d = np.sort(arr2d)
print("Original array:" , arr2d)
print("Sorted array:", sorted_arr2d)
print("Descending array:" , sorted_arr2d[::-1])

Original array: [[3 1 8]
 [6 2 4]]
Sorted array: [[1 3 8]
 [2 4 6]]
Descending array: [[2 4 6]
 [1 3 8]]


### argsort()

In [79]:
marks  =  np.array([40,10,30,20])  #Index positions : [0,1,2,3]

sorted_indices = np.argsort(marks)
sorted_values = np.sort(marks)

print("Original Array:", marks)
print("Sort Values:" , sorted_values)
print("Sorted Indices:" , sorted_indices)

Original Array: [40 10 30 20]
Sort Values: [10 20 30 40]
Sorted Indices: [1 3 2 0]


In [80]:
#2D array

arr = np.array([[30,10,20],
                [80,60,40]])

print("Argsort columns:\n" , np.argsort(arr,axis = 0))
print("Argsort rows:\n" , np.argsort(arr , axis = 1))

Argsort columns:
 [[0 0 0]
 [1 1 1]]
Argsort rows:
 [[1 2 0]
 [2 1 0]]
