## astype()

In [2]:
import numpy as np


In [4]:
arr = np.array([1,2,3,4])
arr_1 = arr.astype(np.float32)
print("Original Array:" , arr,"----->",arr.dtype)
print("Converted Array:", arr_1,"----->",arr_1.dtype)

Original Array: [1 2 3 4] -----> int64
Converted Array: [1. 2. 3. 4.] -----> float32


In [9]:
a = np.array([1,2,3,4])
b = np.array([1,2,3,4,'hello'])
print(a)
print(a.dtype)
print(b)
print(b.dtype)

[1 2 3 4]
int64
['1' '2' '3' '4' 'hello']
<U21


## Random Numbers

In [14]:
#  np.random.rand() : generates random nubebers from 0 to 1

print(np.random.rand())
print("------------------------------")
# 1d array of 5 random element
print(np.random.rand(5))
print("------------------------------")
 #2d array(3rows ,2 colums)
print(np.random.rand(3,2))

0.9586148534192969
------------------------------
[0.65110695 0.04507374 0.55954314 0.03171723 0.4976054 ]
------------------------------
[[0.57329976 0.43241531]
 [0.24247621 0.71748892]
 [0.90491282 0.80063623]]


In [15]:
# np.random.randn()

print(np.random.randn())
print(np.random.randn())
print("------------------------------")
# 1d array of 5 random element
print(np.random.randn(5))
print("------------------------------")
 #2d array(3rows ,2 colums)
print(np.random.randn(3,2))

0.3104986663829244
0.9124693456885866
------------------------------
[-0.94168686  1.28198968 -1.06831637  0.65247628  0.77514569]
------------------------------
[[ 0.81103431 -0.95940016]
 [ 0.95009938 -0.16551926]
 [ 0.02224638 -0.11780246]]


In [18]:
# np.random.randint(start,stop)

a = np.random.randint(1,10,size = 5) # generates between 1 to 9 , no of elements : 5
print(a)

b = np.random.randint(1,10,size = (2,3))  # 2d array
print(b)



[4 2 1 1 6]
[[7 3 3]
 [1 1 2]]


In [20]:
# np.random.unoform()
a = np.random.uniform(1,10,size = 5) # generates between 1 to 9 , no of elements : 5
print(a)

b = np.random.uniform(1,10,size = (2,3))  # 2d array
print(b)



[8.67121252 3.19401723 9.79940337 8.62409302 1.59308933]
[[2.98449581 6.78623101 8.78208635]
 [5.17349005 7.7724538  8.40475414]]


## Indexing

In [25]:
## 1D Array
arr = np.array([10,20,30,40,50])
print("Array:", arr)
print("-" * 20)
print(arr[0])
print(arr[1])
print(arr[2])
print(arr[3])
print(arr[4])
print("-" * 20)
print(arr[-1])
print(arr[-1])
print(arr[-2])
print(arr[-3])
print(arr[-4])

Array: [10 20 30 40 50]
--------------------
10
20
30
40
50
--------------------
50
50
40
30
20


## Slicing

In [28]:
# Slicing : extracting a portion(sub_Array) from the array using the format
arr = np.array([10,20,30,40,50])
print("Array:", arr)
print("------------------------")
print(arr[0:4])
print(arr[0:6:2])
print(arr[::-1])

Array: [10 20 30 40 50]
------------------------
[10 20 30 40]
[10 30 50]
[50 40 30 20 10]


In [35]:
## 2D Array Indexing
arr  = np.array([[10,20,30],
                 [40,50,60],
                 [70,80,80]])
print("2D Array:\n" , arr)
print("------------------------")
print(arr[0,0])
print(arr[0,1])
print(arr[0,2])
print(arr[1,0])
print(arr[1,0])
print(arr[1,1])
print(arr[1,2])
print(arr[2,0])
print(arr[2,1])
print(arr[2,2])
print("-----------------------")
print(arr[-1,-1])
print(arr[-1,-2])
print(arr[-1,-3])
print(arr[-2,-1])
print(arr[-2,-1])
print(arr[-2,-3])

2D Array:
 [[10 20 30]
 [40 50 60]
 [70 80 80]]
------------------------
10
20
30
40
40
50
60
70
80
80
-----------------------
80
80
70
60
60
40


In [47]:
# Slicing
arr  = np.array([[10,20,30],
                 [40,50,60],
                 [70,80,80]])
print("2D Array:\n" , arr)
print("----------------------")
print(arr[0, :]) # extract first row
print(arr[1, :]) # extract second row
print(arr[2, :]) # extract third row
print("---------------------------")
print(arr[: , 0])
print(arr[: , 1])
print(arr[: , 2])
print("----------------------------")
print(arr[0:2 , :])
print("-----------------")
print(arr[0:2 , 0:2])
print("-----------------------")
print(arr[1:3 , :])


2D Array:
 [[10 20 30]
 [40 50 60]
 [70 80 80]]
----------------------
[10 20 30]
[40 50 60]
[70 80 80]
---------------------------
[10 40 70]
[20 50 80]
[30 60 80]
----------------------------
[[10 20 30]
 [40 50 60]]
-----------------
[[10 20]
 [40 50]]
-----------------------
[[40 50 60]
 [70 80 80]]


## Boolean indexing

In [51]:
arr = np.array([1,2,3,4,5,6])

condition = arr > 3
print("Condition (Boolean Array):" , condition)
result = arr[condition]
print("Result"  ,result)

Condition (Boolean Array): [False False False  True  True  True]
Result [4 5 6]


In [52]:
arr = np.array([1,2,3,4,5,6])

print(arr[arr > 3])

[4 5 6]


In [54]:
# 2D Array
arr2d  = np.array([[10,20,30],
                 [40,50,60],
                 [70,80,80]])
print("2D Array:\n" , arr)
print("-------------------")

print("Condition: \n" ,arr2d > 50)
print("Result:" , arr2d[arr2d > 50])



2D Array:
 [1 2 3 4 5 6]
-------------------
Condition: 
 [[False False False]
 [False False  True]
 [ True  True  True]]
Result: [60 70 80 80]


## Updating Numpy Arrays

In [59]:
arr = np.array([10,20,30,40,50])

# Updating single element
arr[0] = 100
print(arr)

#Updating multiple elements
arr[1:3] = 200 , 300
print(arr)

#fancy indexing
arr[[3,4]] = [400 , 500]

# updating using boolean indexing
arr[ arr > 400] = 999
print(arr)


[100  20  30  40  50]
[100 200 300  40  50]
[100 200 300 400 999]


In [70]:
# Updating 2d Array

arr2d  = np.array([[10,20,30],
                 [40,50,60],
                 [70,80,80]])
print("2D Array:\n" , arr)
print("-------------------")
# Update single element
arr2d[0,0] = 100
print(arr2d)
print("--------------------")
arr2d[1]  = [400,500,600]
print(arr2d)
print("---------------------")
arr2d[0:2, 0:2] = [[111,222],
                   [333,444]]
print(arr2d)
print("-------------------------")
arr2d[: , 2] = [333,666,777]
print(arr2d)

#fancy indexing
arr2d[[2,2],[0,1]] = [777,888]
print(arr2d)

# boolean indexing
arr2d[arr2d > 800] = 9999
print(arr2d)
print("-------------------------")

2D Array:
 [100 200 300 400 999]
-------------------
[[100  20  30]
 [ 40  50  60]
 [ 70  80  80]]
--------------------
[[100  20  30]
 [400 500 600]
 [ 70  80  80]]
---------------------
[[111 222  30]
 [333 444 600]
 [ 70  80  80]]
-------------------------
[[111 222 333]
 [333 444 666]
 [ 70  80 777]]
[[111 222 333]
 [333 444 666]
 [777 888 777]]
[[ 111  222  333]
 [ 333  444  666]
 [ 777 9999  777]]
-------------------------


In [77]:
# negative indexing
arr2d  = np.array([[10,20,30],
                 [40,50,60],
                 [70,80,80]])
arr2d[-2:,-2:] = [[500,600],
                  [700,800]]
print(arr2d)

[[ 10  20  30]
 [ 40 500 600]
 [ 70 700 800]]


In [91]:
arr2d  = np.array([[10,20,30],
                 [40,50,60],
                 [70,80,80]])
print(arr2d[-3:-1,-3:-1])
arr2d [-3:-1,-3:-1] = [[300,800],
                       [444,888]]
print(arr2d)

[[10 20]
 [40 50]]
[[300 800  30]
 [444 888  60]
 [ 70  80  80]]
