In [12]:
import numpy as np


In [5]:
arr1 = np.array([1,2,3,4])
print(arr1)
print(type(arr1))

[1 2 3 4]
<class 'numpy.ndarray'>


In [10]:
marks = [10,20,30,40,50]
new_marks = [x+5 for x in marks]
print(new_marks)

[15, 25, 35, 45, 55]


In [15]:
# In numpy: vectorized operation
marks =np.array( [10,20,30,40,50])
marks + 5

array([15, 25, 35, 45, 55])

In [19]:
marks = [10,20,30,40,50]
total = 0
for i in marks:
    total+=i

average  = total/len(marks)
print(average)

30.0


In [22]:
marks = np.array( [10,20,30,40,50])
avg = np.mean(marks)
print(avg)


30.0


In [24]:
print(np.__version__)

2.1.3


In [27]:
arr1 = np.array([1,2,3])
arr2 = np.array([[1,2,3],
                 [4,5,6]])
print(arr1)
print('------------------------------')
print(arr2)

[1 2 3]
------------------------------
[[1 2 3]
 [4 5 6]]


In [39]:
#1D array (single Dimesnison) ----> 1 index
# Vector ----> One Dimensinal array
a = np.array([1,2,3,4,5])
print(a)
print(a.ndim)
print("Shape" , a.shape) # No of elements
print("Size" , a.size) # No of elments

[1 2 3 4 5]
1
Shape (5,)
Size 5


In [41]:
# 2d array(Matrix) ---> 2 indices
b = np.array([[1,2,3,4],
              [5,6,7,8]])
print(b)
print(b.ndim)
print("Shape" , b.shape)
print("Size" , b.size)

[[1 2 3 4]
 [5 6 7 8]]
2
Shape (2, 4)
Shape 8


In [42]:
# 3d array ---> block ,row,column
# Cube or Tensor ---> Three Dimensinal array
c = np.array([[[1,2],
               [3,4]],

              [[5,6],
               [7,8]]])
print(c)
print(c.ndim)
print("Shape" , c.shape) # 2blocks 2 row 2 columns
print("Size" , c.size)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3
Shape (2, 2, 2)
Size 8


## Numpy Built in Functions

In [43]:
# np.zeros() ---> Creates an array filled with 0s
# np.ones() ----> Creats an array filled with 1s
# np.arrange() ---> Creats an array with range of numbers
# np.linspace() ---> Creats an array with evenly spaced numbers
# np.full() ---> Creats an array with specific value
# np.eye() ---> Creats a squared indentiy matrix
# np.diag() ----> Creates a diagnal arrat from a list or extrcst diagnal

In [53]:
print("Zeros:\n" , np.zeros((2,3)))
print("Ones:\n" , np.ones((2,3)))
print("Arange:\n",np.arange(0,11,2))
print("Linspace:\n" , np.linspace(0,1,5))
print("Full:\n",np.full((2,2),9)) 
print("Eye:\n" , np.eye(3))
print("Diagnol:\n" , np.diag([1,2,3]))

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
Arange:
 [ 0  2  4  6  8 10]
Linspace:
 [0.   0.25 0.5  0.75 1.  ]
Full:
 [[9 9]
 [9 9]]
Eye:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Diagnol:
 [[1 0 0]
 [0 2 0]
 [0 0 3]]


In [48]:
for i in range(1,11):
    print(i,end = " ")

1 2 3 4 5 6 7 8 9 10 

## dtype

#### int


In [56]:
arr = np.array([-1,-2,-3] , dtype = np.int32)
print(arr)
print(arr.dtype)

[-1 -2 -3]
int32


In [58]:
arr = np.array([1,2,3] , dtype = np.uint32)
print(arr)
print(arr.dtype)

[1 2 3]
uint32


#### Float

In [60]:
arr = np.array([1.5,2.5,3.5],dtype = np.float64)
print(arr)
print(arr.dtype)

[1.5 2.5 3.5]
float64


#### Complex

In [63]:
# complex64  , complex128
arr = np.array([1+2j , 2+3j, 3+5j],dtype = np.complex64)
print(arr)
print(arr.dtype)

[1.+2.j 2.+3.j 3.+5.j]
complex64


#### Boolean(bool)

In [64]:
#stores True/False

arr = np.array([True , False , True] , dtype = bool)
print(arr)
print(arr.dtype)

[ True False  True]
bool


#### String / Unicode

In [65]:
# stores text values
# dtype = "U1" ----> Unicode string per element
arr = np.array(['a','b','c'] , dtype = 'U1')
print(arr)
print(arr.dtype)

['a' 'b' 'c']
<U1
