In [1]:
import numpy as np

In [7]:
# Logical operator

a = np.array([10,20,30,40])

print(np.logical_and(a>15,a<35))
print(np.logical_or(a<5,a>35))
print(np.logical_not(a>25))

[False  True  True False]
[False False False  True]
[ True  True False False]


## Assignment opretor

In [16]:
# Assignment opretor
a = np.array([10,20,30])
a+=5
print(a)
a-=5
print(a)
a*=2
print(a)
a//=2
print(a)
a%=4
print(a)
a**=2
print(a)


[15 25 35]
[10 20 30]
[20 40 60]
[10 20 30]
[2 0 2]
[4 0 4]


## Numpy Maths

#### sqrt()


In [17]:
import math 

In [19]:
numbers = [4,9,16,25]
b = [math.sqrt(i) for i in numbers]
print(b)

[2.0, 3.0, 4.0, 5.0]


In [22]:
arr = np.array([4,9,16,25])
print(np.sqrt(arr))

[2. 3. 4. 5.]


In [23]:
arr2d = np.array([[4,9],
                 [16,25]])
print(np.sqrt(arr2d))

[[2. 3.]
 [4. 5.]]


#### exp()

In [25]:
print(math.exp(1))
print(math.exp(2))

2.718281828459045
7.38905609893065


In [26]:
arr = np.array([0,1,2,3])
result = np.exp(arr)
print(result)

[ 1.          2.71828183  7.3890561  20.08553692]


In [28]:
arr2d = np.array([[1,2],
                  [3,4]])
result = np.exp(arr2d)
print(result)

[[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]


#### sin,cos

In [32]:
angles_deg = np.array([0,20,45,90])

#converting degrees to radius 
angle_rad = np.deg2rad(angles_deg)

print("Degrees:" , angles_deg)
print("Radius:" , angle_rad)
# sin values
sin_values = np.sin(angle_rad)
print("Sin values:" , sin_values)

Degrees: [ 0 20 45 90]
Radius: [0.         0.34906585 0.78539816 1.57079633]
Sin values: [0.         0.34202014 0.70710678 1.        ]


In [36]:
angles_deg = np.array([[0,30],
                     [45,90]])

#converting degrees to radius 
angle_rad = np.deg2rad(angles_deg)

print("Degrees:" , angles_deg)
print("Radius:" , angle_rad)
# sin values
sin_values = np.sin(angle_rad)
print("Sin values:" , sin_values)
cos_values = np.cos(angle_rad)
print("cos values:" , cos_values)

Degrees: [[ 0 30]
 [45 90]]
Radius: [[0.         0.52359878]
 [0.78539816 1.57079633]]
Sin values: [[0.         0.5       ]
 [0.70710678 1.        ]]
cos values: [[1.00000000e+00 8.66025404e-01]
 [7.07106781e-01 6.12323400e-17]]


In [39]:
angles = np.array([0,np.pi/4, np.pi/3,np.pi/2])
cos_values = np.cos(angles)
print("Angles radiance:" , angles)
print("Cos values:" , cos_values)+

Angles radiance: [0.         0.78539816 1.04719755 1.57079633]
Cos values: [1.00000000e+00 7.07106781e-01 5.00000000e-01 6.12323400e-17]


## add()

In [40]:
#without numpy
a = [1,2]
b = [3,4]
a+b

[1, 2, 3, 4]

In [42]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.add(a,b))

[5 7 9]


In [44]:
a = np.array([[1,2],
              [3,4]])
b = np.array([[5,6],
              [7,8]])
print(np.add(a,b))

[[ 6  8]
 [10 12]]


### subtract()

In [47]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.subtract(b,a))

[3 3 3]


In [48]:
a = np.array([[1,2],
              [3,4]])
b = np.array([[5,6],
              [7,8]])
print(np.subtract(b,a))

[[4 4]
 [4 4]]


### multiply()

In [49]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.multiply(a,b))

[ 4 10 18]


In [50]:
a = np.array([[1,2],
              [3,4]])
b = np.array([[5,6],
              [7,8]])
print(np.multiply(a,b))

[[ 5 12]
 [21 32]]


### divide()

In [51]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.divide(b,a))

[4.  2.5 2. ]


In [54]:
a = np.array([[1,2],
              [3,4]])
b = np.array([[5,6],
              [7,8]])
print(np.divide(b,a))


[[5.         3.        ]
 [2.33333333 2.        ]]


### dot()

In [56]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.dot(a,b))

32


In [57]:
a = np.array([[1,2],
              [3,4]])
b = np.array([[5,6],
              [7,8]])
print(np.dot(a,b))


[[19 22]
 [43 50]]


### @ operator

In [58]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = a@b
print(c)

32


In [60]:
a = np.array([[1,2],
              [3,4]])
b = np.array([[5,6],
              [7,8]])
c = a@b
print(c)

[[19 22]
 [43 50]]


### Numpy Statistics

In [61]:
a = [1,2,3,4]
sum(a)

10

In [62]:
arr = np.array([1,2,3,4,5])
total = np.sum(arr)
print(total)

15


In [66]:
arr2d = np.array([[1,2,3],
              [4,5,6]])
print(np.sum(arr2d))

#sum of rows
print("Sum of rows:" , np.sum(arr2d , axis = 1))
print("Sum of columns:"  , np.sum(arr2d , axis = 0))

21
Sum of rows: [ 6 15]
Sum of columns: [5 7 9]


### min()

In [67]:
arr = np.array([1,2,3,4,5])
minimum = np.min(arr)
print(minimum)

1


In [71]:
arr2d = np.array([[1,2,3],
              [4,5,6]])
print("Min of all elemengts",np.min(arr2d))
print("Min of rows:" , np.min(arr2d , axis = 1))
print("Min of columns:"  , np.min(arr2d , axis = 0))

Min of all elemengts 1
Min of rows: [1 4]
Min of columns: [1 2 3]


### max()

In [73]:
arr = np.array([1,2,3,4,5])
maximum = np.max(arr)
print(maximum)

5


In [74]:
arr2d = np.array([[1,2,3],
              [4,5,6]])
print("Max of all elemengts",np.max(arr2d))
print("Max of rows:" , np.max(arr2d , axis = 1))
print("Max of columns:"  , np.max(arr2d , axis = 0))

Max of all elemengts 6
Max of rows: [3 6]
Max of columns: [4 5 6]
